{% set name = "a3partitioner" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DaanJansen94/a3partitioner/archive/v{{ version }}.tar.gz
  sha456: f65f197005d2f807010fa120bbb8e2f5b460106bf76f165c475b375d42d390b2

build:
  number: 0
  noarch: python
  entry_points:
    - A3Partitioner=a3partitioner.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"
  run_exports:
    - {{ pin_subpackage('a3partitioner', max_pin='x') }}

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6,<4.0
    - biopython >=1.80

test:
  imports:
    - a3partitioner
  commands:
    - A3Partitioner --help

about:
  home: https://github.com/DaanJansen94/a3partitioner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A bioinformatics tool for creating APOBEC3 and non-APOBEC3 partitions
  doc_url: https://github.com/DaanJansen94/a3partitioner/blob/main/README.md

extra:
  recipe-maintainers:
    - DaanJansen94
