{% set name = "a3partitioner" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - biopython
    # Add any other runtime dependencies your package needs

test:
  imports:
    - a3partitioner
  commands:
    - A3Partitioner --help

about:
  home: https://github.com/DaanJansen94/a3partitioner
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A bioinformatics tool for creating APOBEC3 and non-APOBEC3 partitions'

extra:
  recipe-maintainers:
    - DaanJansen94
